/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum HijiriMonths {
  MUHARRAM = 'BILLING.HIJIRI-CALENDAR.MUHARRAM',
  SAFAR = 'BILLING.HIJIRI-CALENDAR.SAFAR',
  RABI_AWWAL = 'BILLING.HIJIRI-CALENDAR.RABI_AWWAL',
  RABI_THANI = 'BILLING.HIJIRI-CALENDAR.RABI_THANI',
  JUMADA_ULA = 'BILLING.HIJIRI-CALENDAR.JUMADA_ULA',
  JUMADA_ALKHIRAH = 'BILLING.HIJIRI-CALENDAR.JUMADA_ALKHIRAH',
  RAJAB = 'BILLING.HIJIRI-CALENDAR.RAJAB',
  SHA_BAN = 'BILLING.HIJIRI-CALENDAR.SHA_BAN',
  RAMADHAN = 'BILLING.HIJIRI-CALENDAR.RAMADHAN',
  SHAWWAL = 'BILLING.HIJIRI-CALENDAR.SHAWWAL',
  THUL_QI_DAH = 'BILLING.HIJIRI-CALENDAR.THUL_QI_DAH',
  THUL_HIJJAH = 'BILLING.HIJIRI-CALENDAR.THUL_HIJJAH'
}
