export class NationalityConstants {

    public static get NATIONALITY_HAVING_IQMA(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_NON_SAUDI_HAVING_IQAMA';
      }
      public static get NATIONALITY_HAVING_BORDERNUMBER(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_NON_SAUDI_HAVING_BORDER_NO';
      }
      public static get NATIONALITY_TRANSACTIONID(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_NON_SAUDI';
      }
      public static get MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI_HAVING_IQAMA(): string {
        return 'MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI_HAVING_IQAMA';
      }
      public static get MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI_HAVING_BORDER_NO(): string {
        return 'MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI_HAVING_BORDER_NO';
      }
      public static get MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES_HAVING_BORDER_NO(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES_HAVING_BORDER_NO';
      }
      public static get MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES_HAVING_IQAMA(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES_HAVING_IQAMA';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES_HAVING_IQAMA(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES_HAVING_IQAMA';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES_HAVING_BORDER_NO(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES_HAVING_BORDER_NO';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_NON_SAUDI_HAVING_IQAMA(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_NON_SAUDI_HAVING_IQAMA';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_NON_SAUDI_HAVING_BORDER_NO(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_NON_SAUDI_HAVING_BORDER_NO';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_GCC_HAVING_IQAMA(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_GCC_HAVING_IQAMA';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_GCC_HAVING_BORDER_NO(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_GCC_HAVING_BORDER_NO';
      }
      public static get MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_GCC(): string {
        return 'MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_GCC';
      }
      public static get MODIFY_NATIONALITY_NON_SAUDI_TO_GCC(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_GCC';
      }

      public static get MODIFY_NATIONALITY_GCC_TO_GCC(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_GCC';
      }
      public static get MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES(): string {
        return 'MODIFY_NATIONALITY_NON_SAUDI_TO_IMMIGRATED_TRIBES';
      }
      public static get MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI(): string {
        return 'MODIFY_NATIONALITY_IMMIGRATED_TRIBES_TO_NON_SAUDI';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_NON_SAUDI(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_NON_SAUDI';
      }
      public static get MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES(): string {
        return 'MODIFY_NATIONALITY_GCC_TO_IMMIGRATED_TRIBES';
      }
      
}