/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum OHTransactionType {
  Injury = 'ADD_INJURY',
  Complication = 'ADD_COMPLICATION',
  CLOSE_COMPLICATION = 'CLOSE_COMPLICATION',
  CLOSE_INJURY = 'CLOSE_INJURY',
  AUDIT_ALLOWANCE = 'INJURY_AUDIT_ALLOWANCE',
  AUDIT_CLAIMS = 'AUDIT_HOS_INVOICE',
  DOCUMENT_TRANSACTION_KEY = 'MANAGE_OH',
  REJECT_INJURY = 'REJECT_INJURY',
  REJECT_COMPLICATION = 'REJECT_COMPLICATION',
  REQUEST_CLARIFICATION = 'REQUEST_TPA_CLARIFICATION',
  REQUEST_CLARIFICATION_FROM_CONTRIBUTOR = 'REQUEST_CLARIFICATION_FROM_CONTRIBUTOR',
  REJECT_OH = 'REJECT_OH',
  REIMBURSEMENT_CLAIM = 'ADD_REIMBURSEMENT_CLAIM',
  DEAD_BODY_REPATRIATION = 'ADD_DEAD_BODY_REPATRIATION',
  TOTAL_DISABILITY_REPATRIATION = 'ADD_TOTAL_DISABILITY_REPATRIATION',
  INJ_DOCUMENT_TRANSACTION_KEY = 'MANAGE_OH',
  REJ_INJ_DOC_TRANSACTION_KEY = 'REJECT_OH',
  UPDATE_ALLOWANCE_PAYEE = 'UPDATE_ALLOWANCE_PAYEE',
  UPDATE_PAYEE = 'UPDATE_PAYEE',
  REQUEST_CLARIFICATION_FROM_TPA ='REQUEST_CLARIFICATION_FROM_TPA'
}
