export class TransactionParams {
  BUSINESS_ID?: number;
  INJURY_ID?: number;
  REGISTRATION_NO?: number;
  NIN?: number;
  SIN?: number;
  REIMBURSEMENT_ID?: number;
  TPA_CODE?: string;
  IDENTIFIER?: string;
  BENEFIT_REQUEST_ID?: number;
  ADJUSTMENT_REPAY_ID?: number;
  MISC_PAYMENT_ID?: number;
  ADJUSTMENT_MODIFICATION_ID?: string;
  REPAY_ID?: number;
  BENEFIT_TYPE?: string;
  CERTIFICATE_NO?: number;
  PENALTY_WAIVER_ID?: number;
  INSTALLMENT_ID?: number;
  CREDIT_REQUEST_NUMBER?: number;
  CONTRACT_ID?: number;
  ENGAGEMENT_ID?: number;
  RECEIPT_NO?: number;
  WAIVERTYPE?: string;
  THIRD_PARTY_ID?: number;
  IQAMA?: number;
  VIOLATION_ID?: number;
  VIOLATION_REQUEST_ID?:number;
  TRANSFER_REQUEST_ID?: number;
  INSPECTION_REF_NUMBER?: string;
  GENERAL_APPEAL? : string;
  MBPROFESSIONALID_ID?: string;
  MBCONTRACT_ID?:string;
  MB_ASSESSMENT_REQUEST_ID?:number;
  APPEAL_ON_VIOLATION_ID?: string;
  MB_DISABILITY_ASSESSMENT_ID?: string;
  PARTICIPANT_TYPE?:string;
  SESSION_ID?:number;
  MB_SESSION_ID?:string;
  MISC_REFERENCE_NO?:number;
}
