/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum WorkFlowStatus {
  GDOSI_RETURN_TO_VALIDATOR1 = 2015,
  FC_RETURN_TO_VALIDATOR1 = 2017,
  FC_RETURN_TO_VALIDATOR2 = 2000,
  FC_RETURN_TO_VALIDATOR2_ = 2000,
  ADMIN_RETURN_TO_VALIDATOR1 = 2008,
  GDOSI_RETURN_TO_VALIDATOR2_ = 2024,
  OH_REJ_PENDING_DOCTOR_APPROVAL = 2026,
  OH_REJ_FINALLY_APPROVED_TPA = 2025,
  OH_MODIFY_FC_RETURN_TO_VALIDATOR1 = 2045,
  REPEN_RETURN = 2048,
  OH_REJ_FINALLY_APPROVED_SYSTEM = 2047,
  OH_REJ_FINALLY_APPROVED_DOCTOR = 2027
}
