export enum BPMMergeUpdateParamEnum {
  ORGANIZATIONUSER = 'TXNElement.Body.organizationUser',
  ORGANIZATION = 'TXNElement.Body.organization',
  ITSMNUMBER = 'TXNElement.Body.itsmNumber',
  RESOLVECOMMENT = 'TXNElement.Body.resolveComment',
  RETURNCOMMENT = 'TXNElement.Body.returnComment',
  ACKCOMMENT = 'TXNElement.Body.ackComment',
  INSPECTIONTYPE = 'TXNElement.Body.inspectionType',
  REJECTION_REASON = 'TXNElement.Body.reasonForRejection',
  ISGCCESTABLISHMENT = 'TXNElement.Body.isGccEstablishment',
  // to be updated as INSTALLMENT_REJECTION_REASON_ARB/INSTALLMENT_REJECTION_REASON_ENG
  REJECTION_REASON_IN_ENG = 'TXNElement.Body.reasonForRejectionEng',
  REJECTION_REASON_IN_ARB = 'TXNElement.Body.reasonForRejectionArb',
  BENEFIT_LATE_REQUEST_REASON_CHANGED = 'TXNElement.Body.lateRequestReasonChanged',
  USER_ID = 'TXNElement.Body.userId',
  ROLE_ID = 'TXNElement.Body.roleId',
  UPDATED_BY = 'TXNElement.Body.updatedBy',
  REQUEST_ROLE_ID = 'Request.Body.roleId',
  REQUEST_USER_ID = 'Request.Body.userId',
  REQUEST_UPDATED_BY = 'Request.Body.updatedBy',
  BENEFIT_LATE_REQUEST_APPROVED = 'TXNElement.Body.lateRequestApproved',
  FOREGOEXPENSES = 'TXNElement.Body.foregoExpenses',
  TPACODE = 'TXNElement.Body.tpaCode',
  COMMENTS = 'TXNElement.Body.comments',
  DOCUMENT = 'TXNElement.Body.document',
  INSTALLMENT_REJECTION_REASON_ARB = 'TXNElement.Body.rejectReasonArb',
  INSTALLMENT_REJECTION_REASON_ENG = 'TXNElement.Body.rejectReasonEng',
  REJECTION_REASON_ARB = 'Request.Body.rejectReasonArb',
  REJECTION_REASON_ENG = 'Request.Body.rejectReasonEng',
  RETURN_REASON_ARB = 'Request.Body.returnReasonArb',
  RETURN_REASON_ENG = 'Request.Body.returnReasonEng',
  REGISTRATION_NO = 'Request.Body.registrationNo',
  REGISTRATION_NO_TXN = 'TXNElement.Body.registrationNo',
  RETURN_REASON_IN_ENG = 'TXNElement.Body.reasonForReturnEng',
  RETURN_REASON_IN_ARB = 'TXNElement.Body.reasonForReturnArb',
  RETURN_ROLE = 'TXNElement.Body.returnRole'
}
