export enum BPMReportName {
  PRIORITY_REPORT = 'PRIORITY_REPORT',
  PRODUCTIVITY_REPORT = 'PRODUCTIVITY_REPORT'
}
export enum BPMInputParameter {
  CREATED_DATE_FROM = 'TASK_CREATED_DATE_FROM',
  CREATED_DATE_TO = 'TASK_CREATED_DATE_TO',
  ASSIGNEE_USERS = 'TASK_ASSIGNEEUSERS',
  PRIORITY = 'PRIORITY'
}
