export enum BPMTransactionStatus {
  COMPLETED = 'COMPLETED',
  ASSIGNED = 'ASSIGNED',
  WITHDRAWN = 'WITHDRAWN',
  REASSIGNED = 'REASSIGNED',
  RETURNED = 'RETURNED',
  STALE = 'STALE',
  SUSPENDED = 'SUSPENDED',
  ACQUIRED = 'ACQUIRED',
  OLABREACHED = 'OLABREACHED'
}
