/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */
export enum TransactionStatus {
  COMPLETED = 'COMPLETED',
  INPROGRESS = 'INPROGRESS',
  REJECTED = 'Rejected',
  APPROVED = 'Approved',
  IN_PROGRESS = 'In Progress',
  DRAFT = 'Draft',
  RESUBMITTED = 'Resubmitted',
  INITIATED = 'Initiated',
  PENDING = 'Pending',
  RETURNED = 'Returned',
  SUBMIT = 'Submit',
  SUSPENDED = 'Suspended',
  APPROVAL_PENDING = 'Pending for Validator Approval',
  ASSIGNED = 'Assigned',
  RESOLVED = 'Resolved',
  DELEGATED = 'Delegated',
  REASSIGNED_TO_DEPT = 'Reassigned to department',
  REASSIGNED = 'Reassigned',
  ON_HOLD = 'On Hold',
  VALIDATED = 'Validated',
  ESCALATED = 'Escalated',
  INFORMATION_REQUESTED = 'Information Requested',
  REOPENED = 'Reopened',
  INFORMATION_PROVIDED = 'Information Provided',
  REQUESTED_ITSM = 'Requested itsm',
  WITHDRAWN = 'Withdrawn',
  RETURN = 'Return',
  AVAILABLE = 'Available',
  CURED_WITH_DISABILITY = 'Cured Without Disability',
  SEND_FOR_INSPECTION = 'Send for inspection',
  CLOSED = 'Closed',
  TRANSACTION_COMPLETED = 'Completed',
  APPEALED = 'Appealed',
  ASSESSMENT_COMPLETED = 'Assessment Completed',
  ASSESSMENT_ACCEPTED_BY_PARTICIPANT = 'Assessment Accepted by participant',
  APPEALED_BY_GOSI = 'Appealed by GOSI',
  APPEALED_BY_PARTICIPANT = 'Appealed by participant/ contributor',
  APPROVED_BY_GOSI_DOCTOR = 'Approved By Gosi Doctor',
  RESCHEDULED_NO_SHOW = 'Rescheduled due to no show',
  RESCHEDULED = 'Rescheduled',
  UNDER_REVIEW = 'Under Review',
  AWAITING_ASSESSMENT_SCHEDULING = 'Awaiting assessment scheduling'
}
