/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum EstablishmentRoutesEnum {
  LOGIN = '/login',
  EST_PROFILE = '/home/establishment/profile',
  PROFILE_SEARCH = '/home/establishment/profile/search',
  VERIFY_REG_ESTABLISHMENT = 'home/establishment/register/verify',
  REGISTER_ESTABLISHMENT = 'home/establishment/register/new',
  VALIDATE_REGISTER_ESTABLISHMENT = 'home/establishment/register/validate',
  REGISTER_PROACTIVE_ESTABLISHMENT = 'home/establishment/register/proactive',
  CHANGE_ESTABLISHMENT = '/home/establishment/change',
  CHANGE_SEARCH_ESTABLISHMENT = '/home/establishment/change/search',
  CHANGE_BASIC_DETAILS = '/home/establishment/change/basic-details',
  EDIT_CHANGE_BASIC_DETAILS = '/home/establishment/change/validate/basic-details',
  ADMIN_EDIT_CHANGE_BASIC_DETAILS = '/home/establishment/change/admin-reenter/basic-details',
  CHANGE_IDENTIFIER_DETAILS = '/home/establishment/change/identifiers',
  EDIT_CHANGE_IDENTIFIER_DETAILS = '/home/establishment/change/validate/identifiers',
  ADMIN_EDIT_CHANGE_IDENTIFIER_DETAILS = '/home/establishment/change/admin-reenter/identifiers',
  CHANGE_BANK_DETAILS = '/home/establishment/change/bank-details',
  EDIT_CHANGE_BANK_DETAILS = '/home/establishment/change/validate/bank-details',
  ADMIN_EDIT_CHANGE_BANK_DETAILS = '/home/establishment/change/admin-reenter/bank-details',
  CHANGE_CONTACT_DETAILS = '/home/establishment/change/contact-details',
  EDIT_CHANGE_CONTACT_DETAILS = '/home/establishment/change/validate/contact-details',
  ADMIN_EDIT_CHANGE_CONTACT_DETAILS = '/home/establishment/change/admin-reenter/contact-details',
  CHANGE_ADDRESS_DETAILS = '/home/establishment/change/address-details',
  EDIT_CHANGE_ADDRESS_DETAILS = '/home/establishment/change/validate/address-details',
  ADMIN_EDIT_CHANGE_ADDRESS_DETAILS = '/home/establishment/change/admin-reenter/address-details',
  CHANGE_MAIN = '/home/establishment/change/branch-to-main',
  VALIDATOR_CHANGE_MAIN = '/home/establishment/change/branch-to-main/modify',
  DELINK = '/home/establishment/change/delink',
  VALIDATOR_MODIFY_DELINK = '/home/establishment/change/delink/modify',
  DELINK_NEW = '/home/establishment/change/delink/new',
  VALIDATOR_MODIFY_DELINK_NEW = '/home/establishment/change/delink/new/modify',
  EST_OWNERS = '/home/establishment/change/owners',
  CHANGE_OWNER = '/home/establishment/change/owners/modify',
  EDIT_CHANGE_OWNER = '/home/establishment/change/validate/owners/modify',
  ADMIN_EDIT_CHANGE_OWNER = '/home/establishment/change/admin-reenter/owners/modify',
  CHANGE_LEGAL_ENTITY = '/home/establishment/change/legal-entity',
  EDIT_CHANGE_LEGAL_ENTITY = '/home/establishment/change/validate/legal-entity',
  ADMIN_EDIT_CHANGE_LEGAL_ENTITY = '/home/establishment/change/admin-reenter/legal-entity',
  CLOSE_ESTABLISHMENT = '/home/establishment/terminate',
  REOPEN_ESTABLISHMENT = '/home/establishment/reopen',
  MODIFY_LATE_FEE = '/home/establishment/change/late-fee',
  VIEW_MOF_PAYMENT = '/home/establishment/change/mof-payment',
  MODIFY_MOF_PAYMENT = '/home/establishment/change/mof-payment/modify',
  ADMIN_TRANSACTION_BACK_ROUTING = '/home/transactions/list/todolist',
  VALIDATOR_REGISTER_ESTABLISHMENT = 'home/establishment/validator/register-establishment',
  VALIDATOR_BASIC_DETAILS = '/home/establishment/validator/basic-details',
  VALIDATOR_IDENTIFIERS = '/home/establishment/validator/identifier-details',
  VALIDATOR_BANK_DETAILS = '/home/establishment/validator/bank-details',
  VALIDATOR_CONTACT_DETAILS = '/home/establishment/validator/contact-details',
  VALIDATOR_CHANGE_OWNER = '/home/establishment/validator/owner-details',
  VALIDATOR_LEGAL_ENTITY = '/home/establishment/validator/legal-entity',
  VALIDATOR_ADDRESS_DETAILS = '/home/establishment/validator/address-details',
  VALIDATOR_CHANGE_MAIN_EST = '/home/establishment/validator/change-main',
  VALIDATOR_CHANGE_MOF_PAYMENT = '/home/establishment/validator/change-mof-payment',
  VALIDATOR_DELINK = '/home/establishment/validator/delink',
  VALIDATOR_LINK_EST = '/home/establishment/validator/link',
  BILL_DASHBOARD_ROUTE = '/home/billing/establishment/dashboard',
  VALIDATOR_TERMINATE = '/home/establishment/validator/terminate',
  VALIDATOR_TERMINATE_MODIFY = '/home/establishment/terminate/modify',
  VALIDATOR_TERMINATE_ADMIN_MODIFY = '/home/establishment/terminate/re-enter',
  VALIDATOR_REPLACE_SUPER_ADMIN = 'home/establishment/validator/manage-admin',
  VALIDATOR_REGISTER_SUPER_ADMIN = 'home/establishment/validator/register-admin',
  TERMINATE = '/home/establishment/terminate',
  REFRESH = 'home/establishment/refresh',
  FLAG = 'home/establishment/flag',
  ADD_FLAG = '/home/establishment/flags/add-flag',
  VALIDATOR_FLAG = '/home/establishment/validator/flag',
  INSURANCE_OP_HEAD_INSPECTION = '/home/establishment/validator/safety-inspection',
  VALIDATOR_LATE_FEE = '/home/establishment/validator/late-fee',
  RASED_DCOUMENT_UPLOAD = '/home/establishment/validator/request-documents',
  DRAFT_ROUTE = 'establishment/transactions/resume',
  MEDICAL_INSURANCE_EXTENSION = '/home/establishment/medical-insurance/medical-insurance-extension',
  MEDICAL_INSURANCE_TERMS = '/home/establishment/medical-insurance/medical-insurance-extension/terms',
  MEDICAL_INSURANCE_ENROLLMENT = 'enroll',
  MEDICAL_INSURANCE_ADD_CONTRIBUTOR = '/home/establishment/medical-insurance/medical-insurance-extension/add-contributor',
  VALIDATOR_RE_OPEN = '/home/establishment/validator/reopen',
  EDIT_REOPENING_DETAILS = '/home/establishment/reopen/modify',
  SC_ADMIN_EVALUATION_TRANSACTION = '/home/establishment/oh-safety/self-evaluation'
}
