export enum EstablishmentWarningKeyEnum {
  ONE_EST_PENDING = 'ESTABLISHMENT.WARNING.PENDING-ONE',
  TWO_EST_PENDING = 'ESTABLISHMENT.WARNING.PENDING-TWO',
  THREE_EST_PENDING = 'ESTABLISHMENT.WARNING.PENDING-THREE',
  ELEVEN_EST_PENDING = 'ESTABLISHMENT.WARNING.PENDING-ELEVEN',
  NO_CURRENT_ACTIVE_GCC_ADMIN = 'ESTABLISHMENT.WARNING.NO-CURRENT-ACTIVE-GCC-ADMIN',
  NO_CURRENT_ACTIVE_SUPER_ADMIN = 'ESTABLISHMENT.WARNING.NO-CURRENT-ACTIVE-SUPER-ADMIN'
}
