export enum EstablishmentKeyEnum {
  GENERATE_CERT_SUCCESS = 'ESTABLISHMENT.CERT-GENERATE-SUCCESSFULL',
  OWNER_DELETE_INFO = 'ESTABLISHMENT.INFO.OWNER-DELETE',
  PAYMENT_SELF_INFO = 'ESTABLISHMENT.INFO.PAYMENT-TO-SELF',
  REPLACE_SUPER_ADMIN = 'ESTABLISHMENT.REPLACE-BRANCH-MANAGER',
  REPLACE_GCC_ADMIN = 'ESTABLISHMENT.REPLACE-GCC-ADMIN',
  CURRENT_SUPER_ADMIN = 'ESTABLISHMENT.CURRENT-SUPER-ADMIN-DETAILS',
  NEW_SUPER_ADMIN = 'ESTABLISHMENT.NEW-SUPER-ADMIN-DETAILS',
  CURRENT_GCC_ADMIN = 'ESTABLISHMENT.CURRENT-GCC-ADMIN-DETAILS',
  NEW_GCC_ADMIN = 'ESTABLISHMENT.NEW-GCC-ADMIN-DETAILS',
  ADD_BRANCH_ADMIN = 'ESTABLISHMENT.ADD-BRANCH-ADMIN',
  NEW_ROLE_ADMIN = 'ESTABLISHMENT.ADD-NEW-ROLE-ADMIN',
  OLD_BRANCH_ADMIN = 'ESTABLISHMENT.REMOVE-BRANCH-ADMIN'
}
