/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

import { RoleIdEnum } from '../enums/role-id-enum';

export class BenefitsGosiShowRolesConstants {
  public static get RESTORE_LUMPSUM_ROLES(): number[] {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE];
  }

  public static get PUBLIC(): number[] {
    return [RoleIdEnum.SUBSCRIBER];
  }

  public static get CSR_MODIFY(): number[] {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.CSR, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }

  public static get NOACCESS_ROLES(): number[] {
    return [
      RoleIdEnum.ROLE_DOCTOR,
      RoleIdEnum.CLM_MGR,
      RoleIdEnum.COLLECTIONS_DEPARTMENT_MANAGER,
      RoleIdEnum.MEDICAL_BOARD_SECRETARY,
      RoleIdEnum.MC_OFFICER,
      RoleIdEnum.MEDICAL_SERVICES_DEPARTMENT_MANAGER,
      RoleIdEnum.BOARD_OFFICER,
      RoleIdEnum.VIOLATION_COMMITTEE_HEAD,
      RoleIdEnum.VIOLATION_COMMITTEE_MEMBER,
      RoleIdEnum.WORK_INJURIES_OCUPATIONAL_DISEASES_DOCTOR,
      RoleIdEnum.WORK_INJURIES_OCCUPATIONAL_DISEASES_SPECIALIST,
      RoleIdEnum.MEDICAL_AUDITOR,
      RoleIdEnum.GD_MS_OS,
      RoleIdEnum.COMPLAINT_MANAGER,
      RoleIdEnum.COMPLAINT_CLERK
    ];
  }

  public static get VIEW_ROLES(): number[] {
    return [
      RoleIdEnum.CSR,
      RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE,
      RoleIdEnum.REGISTRATION_CONTRIBUTIONS_OPERATIONS_OFFICER,
      RoleIdEnum.INS_PROT_EXT_SPVSR,
      RoleIdEnum.GCC_CSR,
      RoleIdEnum.RELATION_OFFICER,
      RoleIdEnum.CALL_CENTRE_AGENT,
      RoleIdEnum.INS_BENF_OFFICER_SPVR,
      RoleIdEnum.REG_CONT_OPER_SPVSR,
      RoleIdEnum.COLLECTION_OFFICER,
      RoleIdEnum.CUSTOMER_CARE_DEPARTMENT_MANAGER,
      RoleIdEnum.CUSTOMER_CARE_DEPARTMENT_HEAD,
      RoleIdEnum.CUSTOMER_CARE_OFFICER,
      RoleIdEnum.CUSTOMER_CARE_SENIOR_OFFICER,
      RoleIdEnum.CUSTOMER_SERVICE_AND_BRANCHES_GENERAL_DIRECTOR,
      RoleIdEnum.CUSTOMER_SERVICE_SUPERVISOR,
      RoleIdEnum.GENERAL_DIRECTOR_FOR_INSPECTION_AND_COLLECTION,
      RoleIdEnum.GDISO,
      RoleIdEnum.GDES,
      RoleIdEnum.INSURANCE_OPERATIONS_MANAGER,
      RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY
    ];
  }

  public static get VALIDATOR_ROLES() {
    return [
      RoleIdEnum.INSURANCE_BENEFIT_SECTION_MANAGER,
      RoleIdEnum.INSURANCE_BENEFIT_OPERATION_OFFICER,
      RoleIdEnum.NEW_VALIDATOR,
      RoleIdEnum.FC,
      RoleIdEnum.INS_PROT_EXT_SPVSR,
      RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE,
      RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO,
      RoleIdEnum.FINANCIAL_CONTROLLER_ANN_ONE,
      RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO
    ];
  }
  public static get BENEFIT_READ() {
    return [RoleIdEnum.BENEFIT_SEARCH_READ, RoleIdEnum.CSR, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }
  public static get SANED_VALIDATOR() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO, RoleIdEnum.SANED_VALIDATION_COMMITTEE];
  }
  public static get SANED_SUSPEND() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO];
  }
  public static get VALIDATOR_OPTION_ROLES() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATION_OFFICER, RoleIdEnum.NEW_VALIDATOR, RoleIdEnum.FC,RoleIdEnum.INS_PROT_EXT_SPVSR, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_ONE, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO];
  }
  public static get CREATE_INDIVIDUAL() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }
  public static get CREATE_PRIVATE() {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO];
  }
  public static get VALIDATOR_ONE() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO];
  }
  public static get SANED_VALIDATOR_EDIT(){
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO];
  }
  public static get VALIDATOR_EDIT() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE];
  }
  public static get VALIDATOR_ONE_FC() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_ONE];
  }
  public static get EDIT_PRIVATE() {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE];
  }
  public static get VIEW_DETAILS() {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }
  public static get BENEFIT_VIEW_DETAILS() {
    return [RoleIdEnum.BENEFIT_SEARCH_READ, RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.SANED_VALIDATION_COMMITTEE, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY, RoleIdEnum.MS_OFFICER];
  }
  public static get CONTRIBUTOR_VISIT_ACCESS() {
      return [RoleIdEnum.INSURANCE_BENEFIT_SECTION_MANAGER, RoleIdEnum.CSR, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }
  public static get DIRECT_PAYMENT_ACCESS() {
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.CSR, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY];
  }
  public static get ADD_AUTHORIZATION_VALIDATOR() {
    return [RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO, RoleIdEnum.ASSISTANT_GOVERNOR, RoleIdEnum.BENEFICIARIES_AND_WORKERS_ABROAD_SECTION_HEAD];
  }
  public static get DIRECT_PAYMENT_HISTORY(){
    return [RoleIdEnum.CUSTOMER_SERVICE_REPRESENTATIVE, RoleIdEnum.CSR, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_ONE, RoleIdEnum.INSURANCE_BENEFIT_OPERATIONAL_OFFICER_TWO, RoleIdEnum.SUBSCRIBER, RoleIdEnum.VIC, RoleIdEnum.BENEFICIARY,RoleIdEnum.FINANCIAL_CONTROLLER_ANN_ONE,RoleIdEnum.FINANCIAL_CONTROLLER_ANN_TWO];
  }
  public static get DOCTOR_DETAILS_EDIT() {
    return [RoleIdEnum.MS_OFFICER, RoleIdEnum.CONTRACTED_DOCTOR,RoleIdEnum.APPEAL_MEDICAL_BOARD_OFFICER];
  }
  public static get DOCTOR_DETAILS_ACTION() {
    return [RoleIdEnum.MS_OFFICER,RoleIdEnum.APPEAL_MEDICAL_BOARD_OFFICER];
  }
}
