export class Address {
  freetextdescription: string = undefined;
  buildingnumber: string = undefined;
  street: string = undefined;
  area: string = undefined;
  city: string = undefined;
  country: string = undefined;
  pobox: number = undefined;
  zipcode: number = undefined;
  careof: string = undefined;
  villagename: string = undefined;
  district: string = undefined;
  region: string = undefined;
  freetextdescription2: string = undefined;
  unitnumber: string = undefined;
  telephonenumber: number = undefined;
  extension: string = undefined;
  additionalnumber: string = undefined;
  countrycode: number = undefined;
  villageid: number = undefined;
  contacttype: string = undefined;
}
