export class EngagementOccupationBean {
  createdby: string = undefined;
  creationtimestamp: string = undefined;
  lastmodifiedby: string = undefined;
  lastmodifiedtimestamp: string = undefined;
  moduleid: number = undefined;
  mode: string = undefined;
  occupationcode: string = undefined;
  occupationdescarb: string = undefined;
  occupationdesceng: string = undefined;
  occupationstartdate: string = undefined;
  occupationstartdateentfmt: string = undefined;
  occupationstartdatestr: string = undefined;
  occupationenddate: string = undefined;
  occupationenddateentfmt: string = undefined;
  occupationenddatestr: string = undefined;
  requestsubmissiondate: string = undefined;
  requestsubmissiondateentfmt: string = undefined;
  requestsubmissiondatestr: string = undefined;
  vicengagementid: string = undefined;
  vicengagementoccupationid: string = undefined;
}
