/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum DueDateWidgetLabels {
  ZERO_DAYS = 'DASHBOARD.DAYS',
  ONE_DAY = 'DASHBOARD.1-DAY',
  TWO_DAYS = 'DASHBOARD.2-DAYS',
  THREE_TO_TEN_DAYS = 'DASHBOARD.3-TO-10-DAYS',
  GRT_THAN_TEN_DAYS = 'DASHBOARD.GRT-THAN-10-DAYS',

  ZERO_HOURS = 'DASHBOARD.HOURS',
  ONE_HOUR = 'DASHBOARD.1-HOUR',
  TWO_HOURS = 'DASHBOARD.2-HOURS',
  THREE_TO_TEN_HOURS = 'DASHBOARD.3-TO-10-HOURS',
  GRT_THAN_TEN_HOURS = 'DASHBOARD.GRT-THAN-10-HOURS',

  ONE_MONTH = 'DASHBOARD.ONE_MONTH',
  TWO_MONTHS = 'DASHBOARD.TWO_MONTHS',
  MORE_THAN_THREE_MONTHS = 'DASHBOARD.MORE_THAN_THREEE_MONTHS'
}
