/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum ChangeEngagementTransactionType {
  JOINING_DATE = 'CHANGE_ENGAGEMENT_JOINING_DATE',
  LEAVING_DATE = 'CHANGE_ENGAGEMENT_LEAVING_DATE',
  BACKDATED_WAGE = 'CHANGE_ENGAGEMENT_BACKDATED_WAGE',
  REGULAR_WAGE = 'CHANGE_ENGAGEMENT_REGULAR_WAGE',
  CURRENT_MONTH_WAGE_FOR_TERMINATED = 'CHANGE_ENGAGEMENT_CURRENT_MONTH_WAGE_FOR_TERMINATED',
  WORKING_ABROAD = 'CHANGE_ENGAGEMENT_WORKING_ABROAD',
  OCCUPATION = 'CHANGE_ENGAGEMENT_OCCUPATION',
  EMPLOYEE_ID = 'CHANGE_ENGAGEMENT_EMPLOYEE_ID',
  WORK_TYPE = 'CHANGE_ENGAGEMENT_WORK_TYPE',
  LEAVING_REASON = 'CHANGE_ENGAGEMENT_LEAVING_REASON'
}
