/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum MonthYearLabel {
  JAN = 'CONTRIBUTOR.MONTH-YEAR.JAN',
  FEB = 'CONTRIBUTOR.MONTH-YEAR.FEB',
  MAR = 'CONTRIBUTOR.MONTH-YEAR.MAR',
  APR = 'CONTRIBUTOR.MONTH-YEAR.APR',
  MAY = 'CONTRIBUTOR.MONTH-YEAR.MAY',
  JUN = 'CONTRIBUTOR.MONTH-YEAR.JUN',
  JUL = 'CONTRIBUTOR.MONTH-YEAR.JUL',
  AUG = 'CONTRIBUTOR.MONTH-YEAR.AUG',
  SEP = 'CONTRIBUTOR.MONTH-YEAR.SEP',
  OCT = 'CONTRIBUTOR.MONTH-YEAR.OCT',
  NOV = 'CONTRIBUTOR.MONTH-YEAR.NOV',
  DEC = 'CONTRIBUTOR.MONTH-YEAR.DEC'
}
