/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */
export enum StatusDateEnum {
  CONTRACT_PENDING_CON = 'PENDING-DATE',
  CONTRACT_APPROVED_CON = 'APPROVED-DATE',
  CONTRACT_APPROVED_SYS = 'APPROVED-DATE',
  CONTRACT_APPROVED_SYS_STATUS = 'APPROVED-DATE',
  CONTRACT_REJECTED_CON = 'REJECTED-DATE',
  CONTRACT_AUTO_CANCELLED = 'AUTO-CANCELLED-DATE',
  CONTRACT_CANCELLED = 'CANCELLED-DATE',
  CONTRACT_EXPIRED = 'EXPIRED-DATE',
  CONTRACT_PENDING_VALIDATOR = 'PENDING-DATE',
  TERMINATED = 'TERMINATED-DATE'
}
