/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

/* System params enum */
export enum SystemParams {
  REG_CONT_MAX_BACKDATED_JOINING_DATE = 'REG_CONT_MAX_BACKDATED_JOINING_DATE',
  REG_CONT_MAX_REGULAR_JOINING_DATE = 'REG_CONT_MAX_REGULAR_JOINING_DATE',
  CHNG_ENG_MAX_BACKDATED_JOINING_DATE = 'CHNG_ENG_MAX_BACKDATED_JOINING_DATE',
  CHNG_ENG_MAX_BACKDATED_PERIOD_START_DATE = 'CHNG_ENG_MAX_BACKDATED_PERIOD_START_DATE',
  CHNG_ENG_MAX_REGULAR_PERIOD_START_DATE = 'CHNG_ENG_MAX_REGULAR_PERIOD_START_DATE',
  TERMINATE_ENG_MAX_BACKDATED_JOINING_DATE = 'TERMINATE_ENG_MAX_BACKDATED_JOINING_DATE',
  TERMINATE_ENG_MAX_REGULAR_JOINING_DATE = 'TERMINATE_ENG_MAX_REGULAR_JOINING_DATE',
  OLD_LAW_DATE = 'OLD_LAW_DATE',
  EINSPECTION_MAX_BACKDATED_JOINING_DATE = 'EINSPECTION_MAX_BACKDATED_JOINING_DATE',
  PPA_CALENDAR_SHIFT_DATE = 'PPA_CALENDAR_SHIFT_DATE',
  PENSION_REFORM_EFFECTIVE_DATE = 'PENSION_REFORM_EFFECTIVE_DATE'
}
