/**
 * Copyright GOSI. All Rights Reserved.
 * This software is the proprietary information of GOSI.
 * Use is subject to license terms.
 */

export enum WorkFlowTypeEnum {
  ADD_CONTRACT = 'ADD CONTRACT',
  CANCEL_CONTRACT = 'CANCEL CONTRACT',
  MANAGE_WAGE = 'MANAGE_WAGE',
  CHANGE_ENGAGMENT = 'CHANGE_ENGAGEMENT',
  REGISTER_CONTRIBUTOR = 'REGISTER_CONTRIBUTOR',
  TERMINATE_CONTRIBUTOR = 'TERMINATE_ENGAGEMENT',
  CANCEL_CONTRIBUTOR = 'CANCEL_ENGAGEMENT',
  ADD_SECONDED = 'REGISTER_SECONDED',
  TRANSFER_CONTRIBUTOR = 'TRANSFER_ENGAGEMENT',
  TRANSFER_ALL_ENGAGEMENT = 'TRANSFER_ALL_ENGAGEMENT',
  BULK_WAGE_UPDATE = 'BULK_WAGE_UPDATE',
  CANCEL_ENGAGEMENT_VIOLATION = 'CANCEL_ENGAGEMENT_VIOLATION',
  CHANGE_ENGAGEMENT_VIOLATION = 'CHANGE_ENGAGEMENT_VIOLATION',
  ADD_VIC = 'REGISTER_VIC_CONTRIBUTOR',
  MANAGE_VIC_WAGE = 'MANAGE_VIC_WAGE',
  TERMINATE_VIC = 'TERMINATE_VIC_ENGAGEMENT',
  CANCEL_VIC = 'CANCEL_VIC_ENGAGEMENT'
}
